specification: "/Users/t.shafigullin/Desktop/Swift/AnalyticsGen/Example/specification/specification.yaml"
source: "schemas"
destination: "generated"
template:
  internal:
    options:
      publicAccess: true
  external:
    options:
      publicAccess: true