source:
 remoteRepo:
    owner: hhru
    repo: hh-mobile-analytics
    defaultBranch: develop
    branchSuffix: ios
    accessToken:
      env: GIT_REMOTE_API_TOKEN
      keychain:
        service: Forgejo Token
        key: hh
platform: iOS
targets:
  - name: Applicant
    path: schemas/applicant
    destination: Features/Applicant/Foundation/ApplicantAnalyticsEvents/Sources/Generated/AnalyticsGen
  - name: HR-Mobile
    path: schemas/hr-mobile
    destination: Features/Employer/Foundation/EmployerAnalyticsEvents/Sources/Generated/AnalyticsGen
  - name: Shared
    path: schemas/shared
    destination: Features/Shared/Foundation/AnalyticsEvents/Sources/Generated/AnalyticsGen
template:
  internal:
    options:
      publicAccess: true
  external:
    options:
      publicAccess: true
