source:
 remoteRepo:
    owner: hhru
    repo: hh-mobile-analytics
    ref:
      finders:
        - type: matched_tag
          source:
            env:
              - GIT_BRANCH
              - GIT_MERGE_BRANCH
            condition:
              type: regex
              value: ^PORTFOLIO-\d+$
          branch_regex: PORTFOLIO-\d+
        - type: matched_tag
          source:
            file:
              - Configurations/Personal.xcconfig
            condition:
              type: regex
              value: ^ANALYTICS_REF = (PORTFOLIO-\d+)$
          branch_regex: PORTFOLIO-\d+
        - type: matched_tag
          source:
            git: current_branch_name
            condition:
              type: regex
              value: ^PORTFOLIO-\d+$
          branch_regex: PORTFOLIO-\d+
        - type: last_merged
          merge_commit_count: 100
          branch_regex: PORTFOLIO-\d+
        - type: last_tag
        - type: last_commit
          branch: master
    accessToken:
      env: GIT_REMOTE_API_TOKEN
      keychain:
        service: Forgejo Token
        key: hh
platform: iOS
targets:
  - name: Applicant
    path: schemas/applicant
    destination: Features/Applicant/Foundation/ApplicantAnalyticsEvents/Sources/Generated/AnalyticsGen
  - name: HR-Mobile
    path: schemas/hr-mobile
    destination: Features/Employer/Foundation/EmployerAnalyticsEvents/Sources/Generated/AnalyticsGen
  - name: Shared
    path: schemas/shared
    destination: Features/Shared/Foundation/AnalyticsEvents/Sources/Generated/AnalyticsGen
template:
  internal:
    options:
      publicAccess: true
  external:
    options:
      publicAccess: true
