specification: "/Users/t.shafigullin/Desktop/Swift/AnalyticsGen/Example/specification/specification.yaml"
source:
  local: "/Users/t.shafigullin/Desktop/Swift/AnalyticsGen/Example/schemas/applicant"
  gitHub: 
    owner: "hhru"
    repo: "hh-mobile-analytics"
    path: "schemas/applicant"
destination: "generated"