source:
  gitHub:
    owner: hhru
    repo: hh-mobile-analytics
    ref:
      finders:
        - type: matched_tag
          source:
            env:
              - GIT_BRANCH
              - GIT_MERGE_BRANCH
            condition:
              type: regex
              value: ^PORTFOLIO-\d+$
          branch_regex: PORTFOLIO-\d+
        - type: matched_tag
          source:
            file:
              - Configurations/Personal.xcconfig
            condition:
              type: regex
              value: ^ANALYTICS_REF = (PORTFOLIO-\d+)$
          branch_regex: PORTFOLIO-\d+
        - type: matched_tag
          source:
            git: current_branch_name
            condition:
              type: regex
              value: ^PORTFOLIO-\d+$
          branch_regex: PORTFOLIO-\d+
        - type: last_merged
          branch: develop
          merge_commit_count: 100
          branch_regex: PORTFOLIO-\d+
        - type: last_tag
        - type: last_commit
          branch: master
    accessToken:
      env: GITHUB_API_TOKEN
      keychain:
        service: GitHub Token
        key: hh
platform: iOS
targets:
  - name: Applicant
    path: schemas/applicant
  - name: HR-Mobile
    path: schemas/hr-mobile
  - name: Shared
    path: schemas/shared
template:
  internal:
    options:
      publicAccess: true
  external:
    options:
      publicAccess: true
