name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Swift
        uses: swift-actions/setup-swift@v1
      - name: Preparation
        run: set -o pipefail
      - name: Build
        run: make build

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Swift
        uses: swift-actions/setup-swift@v1
      - name: Preparation
        run: set -o pipefail
      - name: Build
        run: make build
