name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  macOS:
    name: macOS
    runs-on: macOS-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make build
